### ISSUE TITLE
Govstyles package

### ISSUE THREAD

**Issue by AoifeONeill** [DFoly/ninorap#17]
Finally got round to checking out the repo- looks like you made loads of progress! I noticed you had an issue with Govstyles and wondered if you'd spoken to anyone at GDS about this? I know they'd been doing some work recently on maintaining the package and they'd probs appreciate being made aware :)

**Comment by DFoly** [comment]
Hi Aoife,

Yeah, It wasn't passing the automated testing for some reason. I ended up
just copying
the code from govstyle directly into the package as it was only really one
function
I needed and now it works fine.

I have also been looking at creating the graphs interactive using
a wrapper for a javascript visualisation library. There is also an R package
called govdown which makes it easy to generate static websites using R
and it has the same styling as gov.uk so I think I will play around with
that
a bit as well.

Daniel
